<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib uri="http://htmlcompressor.googlecode.com/taglib/compressor" prefix="compress" %>
<compress:html enabled="true" removeMultiSpaces="true" preserveLineBreaks="true" simpleDoctype="true">
<c:forEach items="${htmlContent}" var="line">
    <c:if test="${fn:contains(line, '</body>')}">
        <%@ include file="includes/yandexmetrika.jsp" %>
    </c:if>
    <c:if test="${fn:contains(line, '<title>')}">
        <c:set var="line" value="${fn:replace(line, '| Virtual tour generated by Panotour', '')}"/></c:if>
    <c:if test="${fn:contains(line, '</head>')}">
<style><compress:css>
        .comodo-logo {
            position: absolute;
            margin-top: -84px;
            width: 100% !important;
        }
        .comodo-logo a {
            float: right !important;
            display: block !important;
            box-sizing: border-box !important;
            margin-right: 5px;
        }</compress:css>
</style>
        <script type="text/javascript"><compress:js> //<![CDATA[
            var tlJsHost = ((window.location.protocol == "https:") ? "https://secure.comodo.com/" : "http://www.trustlogo.com/");
            document.write(unescape("%3Cscript src='" + tlJsHost + "trustlogo/javascript/trustlogo.js' type='text/javascript'%3E%3C/script%3E"));
        //]]></compress:js></script>
    </c:if>
    <c:if test="${fn:contains(line, '<meta name=\"generator\"')}">
        <c:set var="line" value=""/>
    </c:if>
    <c:if test="${fn:contains(line, 'Virtual tour generated by Panotour')}">
        <c:set var="line" value="${fn:replace(line, 'Virtual tour generated by Panotour', '')}"/>
    </c:if>
    ${line.concat(newLine)}
</c:forEach>
</compress:html>