<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Мини-отель «Крым» | Virtual tour generated by Panotour</title>

    <meta name="description" content="Мини-отель «Крым» приглашает отдохнуть на берегу Черного моря. Отель&amp;nbsp;расположен в ближайшем пригороде Ялты в поселке Отрадное. &amp;nbsp;10 минутах ходьбы от оборудованного пляжа, 7 минутах ходьбы от парка-памятника «Прибрежный» и 30 мин. от Набережной г.Ялта. Отель с видом на море и не дорогими номерами в Ялте, гостиница имеет собственный ресторан с летними террасами и панорамным видом на горы и море. Прекрасные и сытные завтраки по меню входят в стоимость проживания в гостинице. Гостям отеля предлагаются блюда европейской и русской кухни, детское меню. Гостевой дом с открытым бассейном, зеленая зона для отдыха, комфортабельные номера с видом на море, видовая терраса для романтического отдыха, детские игрушки, книги для взрослых и детей. Наш гостевой дом Крым приглашает на отдых в Ялту, забронировав номер в нашей гостинице вы получаете недорогие цены на отдых и проживание в Ялте. Желающим провести свой отпуск в Крыму у моря &amp;nbsp;можно остановиться в Мини-отеле «Крым» , который располагает комфортабельными номерами &#39;Люкс&#39; и &#39; Комфорт&#39;&amp;nbsp; с видом на море с открытых террас. А также номерами &amp;nbsp; &#39;Стандарт&#39; с видом на бассейн. И номерами &#39;Эконом&#39; , гости этих номеров могут воспользоваться открытыми террасами отеля. Для семей с детьми отель предлагает приятный бонус в виде размещения детей на дополнительном месте без оплаты (возраст детей до 15 лет). (Virtual tour generated by Panotour)" />

    <meta name="keywords" content="Мини-отель «Крым»,Virtual tour generated by Panotour" />
    <meta name="medium" content="mult" />
    <meta name="video_height" content="480"></meta>
    <meta name="video_width" content="640"></meta>
    <link rel="image_src" href="Mini_Hotel_Crimeadata/thumbnail.jpg" />
    <!-- <meta name="directory" content="PATH/"></meta> -->
    <!-- <link rel="target_url" href="Mini_Hotel_Crimea.html" /> -->
    <meta name="generator" content="Panotour Pro V2.5.5 64bits" />

    <meta name="author" content="FlyStar studio" />

    <meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <style type="text/css">
        @-ms-viewport { width: device-width; }
        @media only screen and (min-device-width: 800px) { html { overflow:hidden; } }
        * { padding: 0; margin: 0; }
        html { height: 100%; }
        body { height: 100%; overflow:hidden; }
        div#container { height: 100%; min-height: 100%; width: 100%; margin: 0 auto; }
        div#tourDIV {
            height:100%;
            position:relative;
            overflow:hidden;
        }
        div#panoDIV {
            height:100%;
            position:relative;
            overflow:hidden;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -o-user-select: none;
            user-select: none;
        }
    </style>
    <!--[if !IE]><!-->
    <script type="text/javascript" src="Mini_Hotel_Crimeadata/lib/jquery-2.1.1.min.js"></script>
    <!--<![endif]-->
    <!--[if lte IE 8]>
    <script type="text/javascript" src="Mini_Hotel_Crimeadata/lib/jquery-1.11.1.min.js"></script>
    <![endif]-->
    <!--[if gt IE 8]>
    <script type="text/javascript" src="Mini_Hotel_Crimeadata/lib/jquery-2.1.1.min.js"></script>
    <![endif]-->


    <style type="text/css">
        div#panoDIV.cursorMoveMode {
            cursor: move;
            cursor: url(Mini_Hotel_Crimeadata/graphics/cursors_move_html5.cur), move;
        }
        div#panoDIV.cursorDragMode {
            cursor: grab;
            cursor: -moz-grab;
            cursor: -webkit-grab;
            cursor: url(Mini_Hotel_Crimeadata/graphics/cursors_drag_html5.cur), default;
        }
    </style>

    <script type="text/javascript">

        function readDeviceOrientation() {
            // window.innerHeight is not supported by IE
            var winH = window.innerHeight ? window.innerHeight : jQuery(window).height();
            var winW = window.innerWidth ? window.innerWidth : jQuery(window).width();
            //force height for iframe usage
            if(!winH || winH == 0){
                winH = '100%';
            }
            // set the height of the document
            jQuery('html').css('height', winH);
            // scroll to top
            window.scrollTo(0,0);
        }
        jQuery( document ).ready(function() {
            if (/(iphone|ipod|ipad|android|iemobile|webos|fennec|blackberry|kindle|series60|playbook|opera\smini|opera\smobi|opera\stablet|symbianos|palmsource|palmos|blazer|windows\sce|windows\sphone|wp7|bolt|doris|dorothy|gobrowser|iris|maemo|minimo|netfront|semc-browser|skyfire|teashark|teleca|uzardweb|avantgo|docomo|kddi|ddipocket|polaris|eudoraweb|opwv|plink|plucker|pie|xiino|benq|playbook|bb|cricket|dell|bb10|nintendo|up.browser|playstation|tear|mib|obigo|midp|mobile|tablet)/.test(navigator.userAgent.toLowerCase())) {
                if(/iphone/.test(navigator.userAgent.toLowerCase()) && window.self === window.top){
                    jQuery('body').css('height', '100.18%');
                }
                // add event listener on resize event (for orientation change)
                if (window.addEventListener) {
                    window.addEventListener("load", readDeviceOrientation);
                    window.addEventListener("resize", readDeviceOrientation);
                    window.addEventListener("orientationchange", readDeviceOrientation);
                }
                //initial execution
                setTimeout(function(){readDeviceOrientation();},10);
            }
        });

        function accessWebVr(){
            unloadPlayer();

            setTimeout(function(){ loadPlayer(true); }, 100);
        }
        function accessStdVr(){
            unloadPlayer();

            setTimeout(function(){ loadPlayer(false); }, 100);
        }
        function loadPlayer(isWebVr) {
            if (isWebVr) {
                embedpano({
                    id:"krpanoSWFObject"
                    ,xml:"Mini_Hotel_Crimeadata/Mini_Hotel_Crimea_vr.xml"
                    ,target:"panoDIV"
                    ,passQueryParameters:true
                    ,bgcolor:"#000000"
                    ,html5:"only+webgl"
                    ,focus: false
                    ,vars:{skipintro:true,norotation:true}
                });
            } else {
                embedpano({
                    id:"krpanoSWFObject"

                    ,swf:"Mini_Hotel_Crimeadata/Mini_Hotel_Crimea.swf"

                    ,target:"panoDIV"
                    ,passQueryParameters:true
                    ,bgcolor:"#000000"
                    ,focus: false

                    ,html5:"prefer"


                });
            }
            //apply focus on the visit if not embedded into an iframe
            if(top.location === self.location){
                kpanotour.Focus.applyFocus();
            }
        }
        function unloadPlayer(){
            if(jQuery('#krpanoSWFObject')){
                removepano('krpanoSWFObject');
            }
        }
        function isVRModeRequested() {
            var querystr = window.location.search.substring(1);
            var params = querystr.split('&');
            for (var i=0; i<params.length; i++){
                if (params[i].toLowerCase() == "vr"){
                    return true;
                }
            }
            return false;
        }
    </script>
</head>
<body>
<div id="container">

    <div id="tourDIV">
        <div id="panoDIV">
            <noscript>

                <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="100%" height="100%" id="Mini_Hotel_Crimeadata/Mini_Hotel_Crimea">
                    <param name="movie" value="Mini_Hotel_Crimeadata/Mini_Hotel_Crimea.swf"/>
                    <param name="allowFullScreen" value="true"/>
                    <!--[if !IE]>-->
                    <object type="application/x-shockwave-flash" data="Mini_Hotel_Crimeadata/Mini_Hotel_Crimea.swf" width="100%" height="100%">
                        <param name="movie" value="Mini_Hotel_Crimeadata/Mini_Hotel_Crimea.swf"/>
                        <param name="allowFullScreen" value="true"/>
                        <!--<![endif]-->
                        <a href="http://www.adobe.com/go/getflash">
                            <img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player to visualize the Virtual Tour : Мини-отель «Крым» (Virtual tour generated by Panotour)"/>
                        </a>
                        <!--[if !IE]>-->
                    </object>
                    <!--<![endif]-->
                </object>

            </noscript>
        </div>

        <script type="text/javascript" src="Mini_Hotel_Crimeadata/Mini_Hotel_Crimea.js"></script>
        <script type="text/javascript">
            if (isVRModeRequested()){
                accessWebVr();
            }else{
                accessStdVr();
            }
        </script>
    </div>
</div>
</body>
</html>