package ru.flystar.travelrk.service;

import lombok.extern.log4j.Log4j;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.springframework.stereotype.Service;
import ru.flystar.travelrk.domain.persistents.ExclusiveTour;
import ru.flystar.travelrk.domain.persistents.Panorama;
import ru.flystar.travelrk.domain.persistents.Scene;

import java.io.File;
import java.io.IOException;

/**
 * Project: travelrk
 * Created by Sergej Shestopalov on 11.12.2017.
 */
@Log4j
@Service
public class HtmlParserService {
    public String parseExclusiveTourHtml(String startscene, String fileNameHtmlExclusiveTour, ExclusiveTour tour, String parameters) {
        Document doc;
        String strHtml = "";
        try {
            doc = Jsoup.parse(new File(fileNameHtmlExclusiveTour), "UTF-8");
            if (doc != null) {
                String tourDir = tour.getPath().replace(".html", "") + "data/";
                String title = doc.title(),
                        description = tour.getDescription(),
                        image = tourDir + "thumbnail.jpg",
                        url = tour.getPath();
                if (startscene != null) {
                    Scene scene = getSceneByName(startscene, tour);
                    title = scene != null ? scene.getTitle() : "";
                    image = tourDir + (scene != null ? scene.getDir() : "") + "/thumbnail_bt.jpg";
                    url += parameters;
                }
                doc.title(title.replace(" | Virtual tour generated by Panotour", ""));
                Element body = doc.select("body").first();
                Element head = doc.select("head").first();
                removeByCssQuery(doc, "meta[name=\"generator\"]");
                removeByCssQuery(doc, "meta[name=\"keywords\"]");
//                removeByCssQuery(doc, "meta[name=\"description\"]");
                removeByCssQuery(doc, "meta[name=\"video_height\"]");
                removeByCssQuery(doc, "meta[name=\"video_width\"]");
                removeByCssQuery(doc, "link[rel=\"image_src\"]");

                addToElement(head, "<link href=\"" + tour.getPath() + "_bt.jpg\" rel=\"image_src\"/>");
                addToElement(head, "<meta property=\"og:title\" content=\"3D тур: " + title + "\"/>");
                addToElement(head, "<meta property=\"og:type\" content=\"article\"/>");
                addToElement(head, "<meta property=\"og:image\" content=\"" + image + "\"/>");
                addToElement(head, "<meta property=\"og:image:width\" content=\"600\"/>");
                addToElement(head, "<meta property=\"og:image:height\" content=\"314\"/>");
                addToElement(head, "<meta property=\"og:url\" content=\"" + url + "\"/>");
                addToElement(head, "<meta property=\"og:site_name\" content=\"TravelRK.ru\"/>");
                addToElement(head, "<meta property=\"og:description\" content=\"" + description + "\"/>");
                addToElement(head, "<meta property=\"fb:app_id\" content=\"1736961283001509\"/>");
//                addToElement(head,"<link href=\"/css/comodo.css\" rel=\"stylesheet\">\n");
//                addToElement(head,"<script language=\"JavaScript\" type=\"text/javascript\" src=\"/js/comodo.js\"/>");
//                addToElement(body,"<div class=\"comodo-logo\"><script language=\"JavaScript\" type=\"text/javascript\">TrustLogo(\"https://travelrk.ru/img/comodo_secure_seal_76x26_transp.png\", \"CL1\", \"none\");</script></div>");
                addToElement(head, "<script language=\"JavaScript\" type=\"text/javascript\" src=\"/js/social.js\"/>");
                addToElement(body, "<script language=\"JavaScript\" type=\"text/javascript\" src=\"/js/yMetrika.js\"/>");
                addToElement(body, "<noscript><div><img src=\"https://mc.yandex.ru/watch/46547013\" style=\"position:absolute; left:-9999px;\" alt=\"\" /></div></noscript>");
                strHtml = doc.outerHtml();
                strHtml = strHtml.replaceAll("Virtual tour generated by Panotour", "");
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return strHtml;
    }

    private Scene getSceneByName(String startscene, ExclusiveTour tour) {
        for (Scene sc : tour.getScenes()) {
            if (sc.getName().equals(startscene)) return sc;
        }
        return null;
    }

    public String parsePanoHtml(String fileNameHtmlPano, Panorama panorama) {
        Document doc;
        String strHtml = "";
        try {
            doc = Jsoup.parse(new File(fileNameHtmlPano), "UTF-8");
            if (doc != null) {
                Element body = doc.select("body").first();
                Element head = doc.select("head").first();
                doc.title(panorama.getTitle());
                addToElement(head, "<link href=\"http://travelrk.ru/images/panoscans/" + panorama.getPanoPath() + "_bt.jpg\" rel=\"image_src\"></link>");
                addToElement(head, "<meta property=\"og:title\" content=\"" + doc.title() + "\"></meta>");
                addToElement(head, "<meta property=\"og:type\" content=\"article\"></meta>");
                addToElement(head, "<meta property=\"og:image\" content=\"https://travelrk.ru/images/panoscans/" + panorama.getPanoPath() + "_bt.jpg\"></meta>");
                addToElement(head, "<meta property=\"og:image:width\" content=\"600\"></meta>");
                addToElement(head, "<meta property=\"og:image:height\" content=\"314\"></meta>");
                addToElement(head, "<meta property=\"og:url\" content=\"http://travelrk.ru/pano/" + panorama.getPanoPath() + "/index.html\"></meta>");
                addToElement(head, "<meta property=\"og:site_name\" content=\"TravelRK.ru\"></meta>");
                addToElement(head, "<meta property=\"og:description\" content=\"" + panorama.getDescription() + "\"></meta>");
                addToElement(head, "<meta property=\"fb:app_id\" content=\"1736961283001509\"></meta>");
//                addToElement(head, "<link href=\"/css/comodo.css\" rel=\"stylesheet\">\n");
//                addToElement(head, "<script language=\"JavaScript\" type=\"text/javascript\" src=\"/js/comodo.js\"/>");
//                addToElement(body, "<div class=\"comodo-logo\"><script language=\"JavaScript\" type=\"text/javascript\">TrustLogo(\"https://travelrk.ru/img/comodo_secure_seal_76x26_transp.png\", \"CL1\", \"none\");</script></div>");
                addToElement(head, "<script language=\"JavaScript\" type=\"text/javascript\" src=\"/js/social.js\"/>");
                addToElement(body, "<script language=\"JavaScript\" type=\"text/javascript\" src=\"/js/yMetrika.js\"/>");
                addToElement(body, "<noscript><div><img src=\"https://mc.yandex.ru/watch/46547013\" style=\"position:absolute; left:-9999px;\" alt=\"\" /></div></noscript>");
                strHtml = doc.outerHtml();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        return strHtml;
    }

    private void addToElement(Element element, String strToAdd) {
        element.append(strToAdd);
    }

    private void removeByCssQuery(Document doc, String cssQuery) {
        Element element = doc.select(cssQuery).first();
        if (element != null) element.remove();
    }
}
